title: Ashrith's page
author: Ashrith Mandayam Athmaram
email: amandayam@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Ashrith's blog page

# social links
twitter_username: ashrithathmaram # DO NOT include the @ character, or else the build will fail!
github_username:  amandayam12 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
